import java.util.ArrayList;
import java.util.List;

/**
 * Created by Tomek Krawczyk on 27.10.2017.
 */

/*
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */

public class problem12 {


   static int getNumberOfdivisiors(int n) {

        int count = 1;

        for (int i = 1; i < Math.sqrt((double) n); i++) {

            if (n % i == 0) {

                count+=2;
            }
        }
        return count;
    }


    static int solution() {


        int triangleNumbers = 0;

        for (int j = 1; j <= 100000000; j++) {

            triangleNumbers = triangleNumbers + j;

            if (getNumberOfdivisiors(triangleNumbers) > 500) {

                System.out.println(triangleNumbers);
                break;


            }

        }return triangleNumbers;
    }

    public static void main(String[] args) {

       solution();


    }
}



